### ISSUE TITLE
방금해서 해봤는데

### ISSUE THREAD

**Issue by hackerj5016** [lhwdev/covid-selftest-macro#29]
다중자가진단은 언제부터 지원 되나요?

**Comment by lhwdev** [comment]
~~한 1억년쯤 후요?~~ 매일 열심히 해당 기능이 추가된 3.0.0 버전을 개발하고 있습니다. 제가 고3이기도 하고, 기다려달라고 하기는 뭐하지만 언젠간 완성되리라 믿습니다.

**Comment by lhwdev** [comment]
필요하다면 이슈를 다시 열어주세요. 일단 닫겠습니다..!
