### ISSUE TITLE
Http error:500

### ISSUE THREAD

**Issue by hackerj5016** [lhwdev/covid-selftest-macro#30]
이거 업뎃전에 뜨던 에러가 발생했어요.
![Screenshot_20220322-062334_ .jpg](https://user-images.githubusercontent.com/76674646/159366296-c3e0cb6f-3997-4bb9-b3d4-a19a4f458f6a.jpg)

**Comment by lhwdev** [comment]
자가진단 사이트의 구조가 변경되어 일어난 오류인거 같네요.
~~디코방에서 같은 오류화면을 한 5분이 보내서 정신이 없네요~~

**Comment by hackerj5016** [comment]
아 그렇군요 답변 감사합니다.
